### ISSUE TITLE
correçao para o bom portugues

### ISSUE THREAD

**Issue by Coyas** [ulisses-cruz/digital#40]
[//]: # (Por favor antes de postar um novo issue, certifique-se que que um issue similar não existe.)

### Este issue irá resolver o seguinte problema:
No banner do site esta  "CABO VERDE DIGITAL NO COMBATE AO COVID-19" mas uma pessoa que tem boa esperiencia com o portugues me alertou que o melhor seria "CABO VERDE DIGITAL NO COMBATE à COVID-19", isto é com acento (esta minuscula porque meu teclado é frances nao tem como por maiuscula

### A solução que sugiro é a seguinte:
Deve mudar o texto no header do site

### Imagen ou screen shot (opcional)
![image](https://user-images.githubusercontent.com/8118827/111849320-d57ff100-88fc-11eb-95c0-1594398ebbbb.png)

**Comment by ulisses-cruz** [comment]
Corrigido
